name: tests
on: [push, pull_request]
jobs:
  test-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      - name: Run tests
        run: bundle exec rake test